[package]
name = "multiwin-demo"
version = "0.1.0"
edition = "2018"
publish = ["crates-io"]

[dependencies]
egui-multiwin = { version = "0.1.11",  path = "../egui-multiwin" }

[[bin]]
name = "example1"
path = "src/main.rs"

[[bin]]
name = "example2"
path = "src/main2.rs"