[package]
name = "egui-multiwin"
version = "0.1.3"
description="A crate that allows for multiple windows with egui"
license = "MIT OR Apache-2.0"
edition = "2018"
publish = ["crates-io"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.22"
egui_glow = { path="../../egui/crates/egui_glow", version = "0.22", features = ["clipboard", "winit", "links"]}
glutin = "0.30.8"
raw-window-handle = "0.5.2"
thiserror = "1.0.40"
